blog/urls.py
from blog.apps import BlogConfig

from django.urls import path

from blog.views import BlogListView, BlogDetailView, BlogCreatView, BlogUpdateView, BlogDeleteView

# from blog.views import

app_name = BlogConfig.name


urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('create/', BlogCreatView.as_view(), name='blog_create'),
    path('<int:pk>/update', BlogUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', BlogDeleteView.as_view(), name='delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from mailing.apps import MailingConfig
from mailing.views import MailingListView, MailingDetailView, MailingUpdateView, MailingDeleteView, MailingCreateView, \
    ClientListView, ClientCreateView, ClientDeleteView, ClientUpdateView, MessageListView, MessageCreateView, \
    MessageDetailView, MessageDeleteView, MessageUpdateView, MainPage, MailingAttemptListView

app_name = MailingConfig.name

urlpatterns = [
    path('home/', cache_page(5)(MainPage.as_view()), name="home"),
    path('', MailingListView.as_view(), name='mailing_list'),
    path('<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('<int:pk>/update', MailingUpdateView.as_view(), name='mailing_update'),
    path('<int:pk>/delete', MailingDeleteView.as_view(), name='mailing_delete'),
    path('create/', MailingCreateView.as_view(), name='mailing_create'),
    path('client/', ClientListView.as_view(), name='client_list'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('client/update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('message/', MessageListView.as_view(), name='message_list'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('message/update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('mailings/<int:mailing_id>/attempts/', MailingAttemptListView.as_view(), name="mailing_attempt_list"),

]

users/urls.py
from users.apps import UsersConfig
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import UserCreateView, email_verification, UserListView, UserUpdateView, UserDeleteView

app_name = UsersConfig.name


urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='login.html'), name='logout'),
    path('register/', UserCreateView.as_view(template_name='login.html'), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('', UserListView.as_view(), name='users_list'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='users_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='users_delete')
]

mailing/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(verbose_name='Email адрес', unique=True)
    full_name = models.CharField(max_length=150, verbose_name='Ф.И.О. клиента')
    сomment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    owner = models.ForeignKey(User, verbose_name='Владелец записи о клиенте', on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    subject = models.CharField(max_length=100, verbose_name='Тема письма')
    message = models.TextField(verbose_name='Сообщение')
    owner = models.ForeignKey(User, verbose_name='Владелец сообщения', on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'


class Mailing(models.Model):
    STATUS_CHOICES = [
        ("created", "Создана"),
        ("started", "Активна"),
        ("completed", "Завершена"),
    ]

    PERIODICITY_CHOICES = [
        ("daily", "Ежедневно"),
        ("weekly", "Еженедельно"),
        ("monthly", "Ежемесячно"),
    ]

    description = models.TextField(verbose_name='Описание', **NULLABLE)
    start_time = models.DateTimeField(verbose_name='Дата начала рассылки')
    periodicity = models.CharField(max_length=10, verbose_name='Периодичность', choices=PERIODICITY_CHOICES)
    status = models.CharField(max_length=10, verbose_name='Статус', choices=STATUS_CHOICES, default='created')
    message = models.ForeignKey(Message, verbose_name='Сообщение', on_delete=models.CASCADE)
    client = models.ManyToManyField(Client, verbose_name='Клиенты')
    actual_end_time = models.DateTimeField(verbose_name='Дата завершения рассылки', **NULLABLE)
    owner = models.ForeignKey(User, verbose_name='Владелец рассылки', on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [('can_edit_status', 'Can edit status'),
                       ('can_view_mailing', 'Can view mailing'),
                       ('can_view_user', 'Can view user')]


class MailingAttempt(models.Model):
    STATUS_CHOICES = [('success', 'Успешно'), ('failed', 'Не успешно')]

    mailing = models.ForeignKey(Mailing, verbose_name='Рассылка', on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    server_response = models.TextField(verbose_name='Ответ почтового сервиса', **NULLABLE)
    send_time = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'Попытка {self.id} для рассылки {self.mailing.id}'

    class Meta:
        verbose_name = 'Попытка'
        verbose_name_plural = 'Попытки'

mailing/forms.py
from django import forms
from mailing.models import Mailing, Client, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'
            if isinstance(field.widget, forms.widgets.DateTimeInput):
                field.widget.input_type = 'datetime-local'


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        exclude = ('owner',)


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('owner',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('owner',)


class MailingModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('status',)

mailing/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from mailing.forms import MailingForm, ClientForm, MessageForm, MailingModeratorForm
from mailing.models import Mailing, Client, Message, MailingAttempt
from django.core.exceptions import PermissionDenied
from django.views import View
from django.shortcuts import render, get_object_or_404

from mailing.services import get_cached_articles


class MainPage(View):
    """Выводит статистику"""
    def get(self, request, *args, **kwargs):
        total_mailings = Mailing.objects.count()
        active_mailings = Mailing.objects.filter(status="started").count()
        unique_clients_count = Client.objects.distinct().count()

        random_articles = get_cached_articles()

        context = {
            "total_mailings": total_mailings,
            "active_mailings": active_mailings,
            "unique_clients_count": unique_clients_count,
            "random_articles": random_articles,
        }

        return render(request, "mailing/home.html", context)


class MailingListView(ListView):
    model = Mailing


class MailingDetailView(DetailView):
    model = Mailing


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_success_url(self):
        return reverse('mailing:mailing_detail', args=[self.kwargs.get('pk')])

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return MailingForm
        if user.has_perm('mailing.can_edit_status'):
            return MailingModeratorForm
        raise PermissionDenied


class MailingDeleteView(DeleteView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')


class MailingCreateView(CreateView, LoginRequiredMixin):
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def form_valid(self, form):
        mailing = form.save(form)
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)


class ClientListView(ListView):
    model = Client


class ClientUpdateView(UpdateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def get_success_url(self):
        return reverse('mailing:client_list')


class ClientDeleteView(DeleteView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    model = Client
    success_url = reverse_lazy('mailing:client_list')


class ClientCreateView(CreateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        client = form.save(form)
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)


class MessageListView(ListView):
    model = Message


class MessageDetailView(DetailView):
    model = Message


class MessageDeleteView(DeleteView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    model = Message
    success_url = reverse_lazy('mailing:message_list')


class MessageCreateView(CreateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')

    def form_valid(self, form):
        message = form.save(form)
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(UpdateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')

    def get_success_url(self):
        return reverse('mailing:message_list')


class MailingAttemptListView(LoginRequiredMixin, ListView):
    model = MailingAttempt
    template_name = "mailing/mailing_attempt_list.html"
    context_object_name = "attempts"

    def get_queryset(self):
        mailing_id = self.kwargs["mailing_id"]
        return MailingAttempt.objects.filter(mailing_id=mailing_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing_id = self.kwargs["mailing_id"]
        context["mailing"] = get_object_or_404(Mailing, pk=mailing_id)
        context["mailing_id"] = mailing_id
        return context

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Рассылки своими руками</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">Рассылки своими руками</h4>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Аккаунт</h4>
                    <ul class="list-unstyled">
                        </li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'users:logout' %}" class="text-white">Выйти</a></li>
                        {% else %}
                        <li><a href="{% url 'users:login' %}" class="text-white">Войти</a></li>
                        <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <style>.custom-link {
                color: white
            }</style>
            <li><a href="{% url 'mailing:home' %}" class="nav-link px-2 custom-link">Главная</a></li>
            <li><a href="{% url 'mailing:mailing_list' %}" class="nav-link px-2 custom-link">Рассылки</a></li>
            <li><a href="{% url 'mailing:message_list' %}" class="nav-link px-2 custom-link">Сообщения</a></li>
            <li><a href="{% url 'mailing:client_list' %}" class="nav-link px-2 custom-link">Клиенты</a></li>
                        <li><a href="{% url 'blog:blog_list' %}" class="nav-link px-2 custom-link">Блог</a></li>
                {% if perms.mailing.can_edit_status %}
                <li><a href="{% url 'users:users_list' %}" class="nav-link px-2 custom-link">Пользователи</a></li>
            {% endif %}
        </ul>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">

                <span class="navbar-toggler-icon"></span>
            </button>
        </div>

    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Рассылки своими руками</h1>


        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            {% block content %}
            {% endblock %}

        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">

        <p>2024</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{%static 'js/popper.min.js' %}"></script>
<script src="{%static 'js/bootstrap.min.js' %}"></script>
<script src="{%static 'js/holder.min.js' %}"></script>
</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить клиента "{{object.full_name}}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a class="btn btn-warning" href="{% url 'mailing:client_list'%}">Отмена</a>

                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <div class="card-body">


                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>

                    </div>
                </div>

                <div class="col-6">
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                            <hr>
                        {% endif %}
                    {% endfor %}
                        </button>

                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<a href="{% url 'mailing:client_create' %}" type="button" class="btn  btn-success my-2">Создать Клиента</a>
{% else %}
<h5>Что бы увидеть список своих клиентов, зайдите на свой аккаунт</h5>

<li><a href="{% url 'users:login' %}" class="text-black">Войти</a></li>

{% endif %}
{% for object in object_list %}
{% if object.owner == user or user.is_superuser %}
<div class="col-md-12">
    <div class="card mb-4 box-shadow">

        <div class="card-body">
            <p class="card-text"> Клиент "{{ object.full_name }}"</p>
            <p class="card-text"> Email "{{ object.email }}"</p>
            <p class="card-text"> Создал "{{ object.owner }}"</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">

                    <a href="{% url 'mailing:client_update' object.pk %}" type="button" class="btn  btn-warning my-2">Редактировать</a>
                    <a href="{% url 'mailing:client_delete' object.pk %}" type="button" class="btn  btn-danger my-2">Удалить</a>
                </div>
                <small class="text-muted">9 mins</small>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}
{% endblock %}

mailing/templates/mailing/home.html
{% extends 'mailing/base.html' %}

{% load static %}

{% block content %}
    <!-- Статистика -->
    <div class="container">
        <div class="statistics">
            <h2>Статистика</h2>
            <div class="stat-item">
                <p><strong>Количество рассылок всего:</strong> {{ total_mailings }}</p>
            </div>
            <div class="stat-item">
                <p><strong>Количество активных рассылок:</strong> {{ active_mailings }}</p>
            </div>
            <div class="stat-item">
                <p><strong>Количество уникальных клиентов для рассылок:</strong> {{ unique_clients_count }}</p>
            </div>
        </div>
    </div>

    <!-- Случайные статьи -->
    <div class="container">
        <div class="random-articles">
            <h2>Случайные статьи</h2>
            <div class="row articles-grid">
                {% if random_articles %}
                    {% for blog in random_articles %}
                        <div class="col-md-3 mb-4"> <!-- Используем класс mb-4 для нижнего отступа -->
                            <div class="card" style="width: 100%;"> <!-- Установлено 100% для ширины карточки -->
                                {% if blog.image %}
                                    <img src="{{ blog.preview_image.url }}" class="card-img-top" alt="{{ blog.title }}">
                                {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title">{{ blog.title }}</h5>
                                    <p class="card-text">{{ blog.body | truncatechars:100 }}...</p>
                                    <a href="{% url 'blog:blog_detail' blog.pk %}" class="btn btn-primary">Читать</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>Нет доступных статей.</p>  <!-- Сообщение, если нет статей -->
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

mailing/templates/mailing/mailing_attempt_list.html
{% extends 'mailing/base.html' %}

{% block content %}
    <h5>Список попыток рассылки: {{ mailing.description }}</h5>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>№</th>
            <th>Время создания</th>
            <th>Статус</th>
            <th>Ответ сервера</th>
        </tr>
        </thead>
        <tbody>
        {% for attempt in attempts %}
            <tr>
                <td>{{ attempt.id }}</td>
                <td>{{ attempt.send_time }}</td>
                <td>{{ attempt.status }}</td>
                <td>{{ attempt.server_response }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5">Пока нет попыток рассылок.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="text-center mt-3">
        <a href="{% url 'mailing:mailing_detail' mailing.pk %}" class="btn btn-primary">Назад</a>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить рассылку "{{object.message}}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a class="btn btn-warning" href="{% url 'mailing:mailing_list'%}">Отмена</a>

                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-md-12">
    <div class="card mb-4 box-shadow">

        <div class="card-body">
            <p class="card-text"> Рассылка "{{ object.message }}"</p>
            <p class="card-text"> Сообщение "{{ object.message.message }}"</p>
            <p class="card-text"> Описание рассылки "{{ object.description }}"</p>
            <p class="card-text"> Начало рассылки "{{ object.start_time }}"</p>
            <p class="card-text"> С какой периодичностью направляется рассылка "{{ object.periodicity }}"</p>
            <p class="card-text"> Статус "{{ object.status }}"</p>
            <p class="card-text"> Дата завершения рассылки "{{ object.actual_end_time }}"</p>
            <p class="card-text"> Создал "{{ object.owner }}"</p>

            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'mailing:mailing_list'%}" type="button" class="btn  btn-primary my-2">Назад</a>
                    <a href="{% url 'mailing:mailing_attempt_list' mailing.pk %}" type="button" class="btn  btn-info my-2">История рассылки</a>
                    {% if perms.mailing.can_edit_status and not user.is_superuser  %}
                    <a href="{% url 'mailing:mailing_update' object.pk %}" type="button" class="btn  btn-warning my-2">Управлять рассылкой</a>
                    {% else %}
                    <a href="{% url 'mailing:mailing_update' object.pk %}" type="button" class="btn  btn-warning my-2">Редактировать</a>
                    {% endif %}
                    {% if object.owner == user or user.is_superuser %}
                    <a href="{% url 'mailing:mailing_delete' object.pk %}" type="button" class="btn  btn-danger my-2">Удалить</a>
                    {% endif %}</div>
                <small class="text-muted">9 mins</small>
            </div>
        </div>

    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <div class="card-body">


                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>

                    </div>
                </div>

                <div class="col-6">
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                            <hr>
                        {% endif %}
                    {% endfor %}
                        </button>

                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<a href="{% url 'mailing:mailing_create' %}" type="button" class="btn  btn-success my-2">Создать рассылку</a>
{% else %}
<h5>Что бы увидеть список своих рассылок, зайдите на свой аккаунт</h5>

<li><a href="{% url 'users:login' %}" class="text-black">Войти</a></li>

{% endif %}
{% for object in object_list %}
{% if object.owner == user or user.is_superuser or perms.mailing.can_edit_status %}
<div class="col-md-12">
    <div class="card mb-4 box-shadow">

        <div class="card-body">
            <p class="card-text"> Рассылка "{{ object.description }}"</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'mailing:mailing_detail' object.pk %}" type="button" class="btn  btn-primary my-2">Посмотреть</a>
                    {% if perms.mailing.can_edit_status and not user.is_superuser and object.owner != user %}
                    <a href="{% url 'mailing:mailing_update' object.pk %}" type="button" class="btn  btn-warning my-2">Управлять рассылкой</a>
                    {% else %}
                    <a href="{% url 'mailing:mailing_update' object.pk %}" type="button" class="btn  btn-warning my-2">Редактировать</a>
                    {% endif %}
                    {% if object.owner == user or user.is_superuser %}
                    <a href="{% url 'mailing:mailing_delete' object.pk %}" type="button" class="btn  btn-danger my-2">Удалить</a>
                    {% endif %}
                </div>
                <small class="text-muted">9 mins</small>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-md-12">
    <div class="card mb-4 box-shadow">

        <div class="card-body">
            <p class="card-text"> Рассылка "{{ object.subject }}"</p>
            <p class="card-text"> Сообщение "{{ object.message }}"</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'mailing:message_list'%}" type="button" class="btn  btn-primary my-2">Назад</a>
                    {% if not perms.mailing.can_edit_status %}
                    <a href="{% url 'mailing:message_update' object.pk %}" type="button" class="btn  btn-warning my-2">Редактировать</a>
                    <a href="{% url 'mailing:message_delete' object.pk %}" type="button" class="btn  btn-danger my-2">Удалить</a>
                    {% endif %} </div>
                <small class="text-muted">9 mins</small>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<a href="{% url 'mailing:message_create' %}" type="button" class="btn  btn-success my-2">Создать сообщение</a>
{% else %}
<h5>Что бы увидеть список своих сообщений, зайдите на свой аккаунт</h5>

<li><a href="{% url 'users:login' %}" class="text-black">Войти</a></li>

{% endif %}
{% for object in object_list %}
{% if object.owner == user or user.is_superuser or perms.mailing.can_edit_status %}
<div class="col-md-12">
    <div class="card mb-4 box-shadow">

        <div class="card-body">
            <p class="card-text"> Сообщение для рассылки "{{ object.subject }}"</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'mailing:message_detail' object.pk %}" type="button" class="btn  btn-primary my-2">Посмотреть</a>
                    {% if user.is_superuser or object.owner == user%}
                    <a href="{% url 'mailing:message_update' object.pk %}" type="button" class="btn  btn-warning my-2">Редактировать</a>
                    <a href="{% url 'mailing:message_delete' object.pk %}" type="button" class="btn  btn-danger my-2">Удалить</a>
                    {% endif %}
                </div>
                <small class="text-muted">9 mins</small>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}
{% endblock %}