blog/urls.py
from blog.apps import BlogConfig

from django.urls import path

from blog.views import BlogListView, BlogDetailView, BlogCreatView, BlogUpdateView, BlogDeleteView

# from blog.views import

app_name = BlogConfig.name


urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('create/', BlogCreatView.as_view(), name='blog_create'),
    path('<int:pk>/update', BlogUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', BlogDeleteView.as_view(), name='delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name="Заголовок",
                             help_text="Введите название продукта")
    description = models.TextField(
        verbose_name="Содержимое", help_text="Введите содержимое блога"
    )
    image = models.ImageField(
        upload_to="images/",
        blank=True,
        null=True,
        verbose_name="Превью",
        help_text="Загрузите изображение",
    )
    created_at = models.DateTimeField(blank=True, null=True, verbose_name="Дата создания(записи в БД)")
    views_count = models.IntegerField(default=0, verbose_name="количество просмотров")
    owner = models.ForeignKey(User, verbose_name='Владелец блога', on_delete=models.CASCADE, **NULLABLE)

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"
        ordering = ["title", "-created_at"]

    def __str__(self):
        return self.title

blog/forms.py
from django.forms import ModelForm
from mailing.forms import StyleFormMixin
from blog.models import Blog


class BlogForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Blog
        exclude = ('views_count', 'owner')

blog/views.py
from django.urls import reverse

from blog.forms import BlogForm
from blog.models import Blog
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


class BlogCreatView(CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        message = form.save(form)
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1

        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailing/base.html' %}
{% load blog_tags %}
{% block content%}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить статью "{{object.title}}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a class="btn btn-warning" href="{% url 'blog:blog_list'%}">Отмена</a>

                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailing/base.html' %}
{% load blog_tags %}
{% block content %}
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm">
                <img src="{{ blog.image  | media_filter }}">
                <div class="card-body">
                    <p class="card-text">{{ object.title }}</p>
                    <p class="card-text">Описание: {{ object.description }} </p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'blog:blog_list'%}" role="button">Назад</a>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                Просмотры: {{ object.views_count}}
            </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing/base.html' %}
{% load blog_tags %}
{% block content%}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/base.html' %}
{% load blog_tags %}
{% block content %}
<div class="container">
    <div class="col-12">

        {% if user.is_authenticated %}
        <a class="btn btn-outline-primary mb-5" href="{% url 'blog:blog_create' %}">Добавить статью</a>
        {% endif %}
                <h3>Статьи блога</h3>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for blog in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img src="{{ blog.image  | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">{{ blog.title }}</p>
                        <p class="card-text">Описание: {{ blog.description | truncatechars:100 }} </p>
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'blog:blog_detail' blog.pk%}"
                               role="button">Посмотреть статью</a>
                            {% if user.is_superuser or blog.owner == user%}
                            <a class="btn btn-warning" href="{% url 'blog:update' blog.pk%}"
                               role="button">Изменить</a>
                            <a class="btn btn-danger" href="{% url 'blog:delete' blog.pk%}"
                               role="button">удалить</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}