blog/urls.py
from blog.apps import BlogConfig

from django.urls import path

from blog.views import BlogListView, BlogDetailView, BlogCreatView, BlogUpdateView, BlogDeleteView

# from blog.views import

app_name = BlogConfig.name


urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('create/', BlogCreatView.as_view(), name='blog_create'),
    path('<int:pk>/update', BlogUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', BlogDeleteView.as_view(), name='delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from mailing.apps import MailingConfig
from mailing.views import MailingListView, MailingDetailView, MailingUpdateView, MailingDeleteView, MailingCreateView, \
    ClientListView, ClientCreateView, ClientDeleteView, ClientUpdateView, MessageListView, MessageCreateView, \
    MessageDetailView, MessageDeleteView, MessageUpdateView, MainPage, MailingAttemptListView

app_name = MailingConfig.name

urlpatterns = [
    path('home/', cache_page(5)(MainPage.as_view()), name="home"),
    path('', MailingListView.as_view(), name='mailing_list'),
    path('<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('<int:pk>/update', MailingUpdateView.as_view(), name='mailing_update'),
    path('<int:pk>/delete', MailingDeleteView.as_view(), name='mailing_delete'),
    path('create/', MailingCreateView.as_view(), name='mailing_create'),
    path('client/', ClientListView.as_view(), name='client_list'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('client/update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('message/', MessageListView.as_view(), name='message_list'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('message/update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('mailings/<int:mailing_id>/attempts/', MailingAttemptListView.as_view(), name="mailing_attempt_list"),

]

users/urls.py
from users.apps import UsersConfig
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import UserCreateView, email_verification, UserListView, UserUpdateView, UserDeleteView

app_name = UsersConfig.name


urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='login.html'), name='logout'),
    path('register/', UserCreateView.as_view(template_name='login.html'), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('', UserListView.as_view(), name='users_list'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='users_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='users_delete')
]

users/models.py
from django.contrib.auth.models import AbstractUser

from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    token = models.CharField(max_length=100, verbose_name='Токен', null=True, blank=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

users/forms.py
from mailing.forms import StyleFormMixin
from django.contrib.auth.forms import UserCreationForm
from users.models import User
from django import forms


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'


class UserModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('is_active',)

users/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404, redirect
from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserForm, UserModeratorForm
from users.models import User
import secrets
from django.core.mail import send_mail
from django.core.exceptions import PermissionDenied


class UserCreateView(CreateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}'
        send_mail(
            subject="Подтверждение почты",
            message=f"Привет, перейди по ссылке для потвердления почты {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class UserListView(ListView):
    model = User


class UserUpdateView(UpdateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:users_list')

    def get_success_url(self):
        return reverse('users:users_list')

    def get_form_class(self):
        user = self.request.user
        if user.is_superuser:
            return UserForm
        if user.has_perm('mailing.can_edit_status') and not user.is_superuser:
            return UserModeratorForm
        raise PermissionDenied


class UserDeleteView(DeleteView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    model = User
    success_url = reverse_lazy('users:users_list')

users/templates/users/user_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить пользователя "{{object.email}}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a class="btn btn-warning" href="{% url 'users:users_list'%}">Отмена</a>

                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <div class="card-body">


                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>

                    </div>
                </div>

                <div class="col-6">
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                            <hr>
                        {% endif %}
                    {% endfor %}
                        </button>

                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<a href="{% url 'mailing:message_create' %}" type="button" class="btn  btn-success my-2">Создать сообщение</a>
{% for object in object_list %}
{% if object.owner == user or perms.mailing.can_edit_status%}
<div class="col-md-12">
    <div class="card mb-4 box-shadow">

        <div class="card-body">
            <p class="card-text"> Пользователь "{{ object.email }}"</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    {% if user.is_superuser %}
                    <a href="{% url 'users:users_update' object.pk %}"
                       type="button" class="btn  btn-warning my-2">Редактировать</a>
                    <a href="{% url 'users:users_delete' object.pk %}"
                       type="button" class="btn  btn-danger my-2">Удалить</a>
                    {% else %}
                    <a href="{% url 'users:users_update' object.pk %}"
                       type="button" class="btn  btn-warning my-2">Отключить пользователя</a>
                    {% endif %}
                </div>
                <small class="text-muted">9 mins</small>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}
{% endblock %}